name: "Build SSSG site"
description: "Build a static site with SSSG"
branding:
  icon: "command"
  color: "orange"
inputs:
  source:
    description: "Source directory"
    required: true
  target:
    description: "Target directory"
  filesAsDirs:
    description: "Convert bare files to directories"
  ignore:
    description: "Ignore paths (comma seperated)"
  customizerPath:
    description: "Path to a customizer module"
runs:
  using: "docker"
  image: "docker://ghcr.io/cheeplusplus/simplestaticsitegen/simplestaticsitegen:latest"
