name: Docker Image CI

on:
  push:
    branches:
      - 'master'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Publish to Registry
        if: success()
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}/simplestaticsitegen
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          no_push: ${{ github.event_name == 'pull_request' || github.actor == 'dependabot[bot]' }}
